### PR TITLE
Automatic Region Detection

### PR DESCRIPTION
**Pull request by raysun**
First - hi, cool app, perfect for my Splatooning needs - I was about to start writing something similar when I found your project. Thought I could help out with your project instead. On an unrelated side note, I built a small [Twitter bot](https://twitter.com/SplatoonMode) a few days ago to just track zone changes.

Now, on to this actual code change:
Sets the Splatoon region based on the device's region (Settings > General > Language & Region > Region). This only runs the first time the app is launched. If the user changes his region manually later, we do not overwrite it.

The only real code changes are in TabViewController.m and the HZCountryToContinentDecoder support files.

### CODE REVIEW

**Comment by OatmealDome** [comment]
Hey, thanks for your interest in the app and your contribution! I'll look at this shortly.

**Comment by raysun** [comment]
Oh, and I added push notifications:
img_0352

It's not really ready yet, though, since I'm using OneSignal's backend for APNS. But I have a Python script that can parse splatoon.ink's JSON, and it can be extended to call OneSignal and APNS from AWS.

Let's discuss - I'm raysun@gmail.com.

And if you like working on Nintendo-related projects, I'm also working on this: http://raysun.info/makemelink/

**Comment by OatmealDome** [comment]
Hey, just merged your pull request. I wrote a push server in Java already, though I am actually still interested in the Python script. (though I'm a bit hesitant to use a third party notification service when I'm only going to support iOS devices). I'll shoot you an e-mail in a bit.

**Comment by raysun** [comment]
Cool. Yeah, if you have a custom APNS solution that works without a service provider, that definitely sounds better. 

I read in your app update that you have a backup solution to splatoon.ink’s JSON - can you tell me about that? Also, do you know why splatoon.ink stopped updating at the New Year?

I have a backup solution that uses https://splatoon.nintendo.net/schedule.json <https://splatoon.nintendo.net/schedule.json> - it requires authentication, so my script logs in with a throwaway NNID that I set up on the Wii U, like this:

-----
payload = {'username': 'johnpetersonrock', 'password': ‘<removed for now>'}
url = ‘<https://id.nintendo.net <https://id.nintendo.net/> URL that logs me in>''
headers = {'Accept-Language': 'en-US'}
mainpage = requests.post(url, data=payload, headers=headers)
cookies = {'_wag_session': mainpage.cookies['_wag_session']}

then you can load the JSON above with the auth cookie

**Comment by OatmealDome** [comment]
Hah, funny you mentioned SplatNet. [My backup method](https://github.com/OatmealDome/SplatStages/blob/master/SplatStagesFramework/SplatDataFetcher.m#L118) also uses SplatNet :p

I have no idea why splatoon.ink just stopped updating. I have no contact with the maintainer, so unless they announce something I guess we'll never find out...

**Pull request merged**
